jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8080
   servlet:
      session:
         timeout: 21600s

spring:
   h2:
      console:
         enabled: true
         path: /h2
   datasource:
      driver-class-name: org.h2.Driver
      type: com.zaxxer.hikari.HikariDataSource
      jdbcUrl: jdbc:h2:mem:~/alquilerMotos
      username: sa
      password: sa
      hikari:
         poolName: pool
